import { fab } from "@fortawesome/free-brands-svg-icons";
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faCheck,
  faCode,
  faEnvelope,
  faLink,
  faMobileAlt,
  faPencilRuler,
  faRecycle,
  faSearch,
  faServer,
  faSitemap,
  faStar,
  faSwatchbook,
  faTable,
  faCloudUploadAlt,
  faLeaf,
  faDatabase,
  faProjectDiagram,
  faBoxes,
  faMicrochip,
  faCoins,
  faGlobe,
  faUserTie,
  faBug,
  faMobileScreenButton,
  faBars,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(fab);
library.add(
  faBars,
  faBoxes,
  faBug,
  faCheck,
  faCloudUploadAlt,
  faCode,
  faCoins,
  faDatabase,
  faEnvelope,
  faGlobe,
  faLeaf,
  faLink,
  faMicrochip,
  faMobileAlt,
  faMobileScreenButton,
  faPencilRuler,
  faProjectDiagram,
  faRecycle,
  faSearch,
  faServer,
  faSitemap,
  faStar,
  faSwatchbook,
  faTable,
  faUserTie
);
